
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mgj
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
     initial-size: 20
     min-idle: 10
     max-active: 30
     max-wait: 60000
     time-between-eviction-runs-millis: 60000
  resources:
    static-locations: classpath:/public,classpath:/static,file:d:/
    
server:
  port: 8809
  servlet:
    context-path: /xm
 
mybatis:
  mapper-locations: classpath:/mps/*.xml

     